# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Fast, disk space efficient package manager
brew "pnpm"
# Python version management
brew "pyenv"
# Rsync for cloud storage
brew "rclone"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Generate your Xcode project from a spec file and your folder structure
brew "xcodegen"
# Desktop password and login vault
cask "bitwarden"
# Web browser
cask "firefox"
# Web browser
cask "google-chrome"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Peer to peer Bitorrent client
cask "qbittorrent"
# System monitor for the menu bar
cask "stats"
